export * from './registry.js';
export * from './passes/preserve-type-illusions.js';
export * from './passes/generic-confusion.js';
export * from './passes/decorator-aware-lowering.js';
export * from './passes/namespace-virtualization.js';
export * from './passes/type-level-fake-path.js';
export * from './passes/symbol-indirection.js';
export * from './passes/string-pool-encoding.js';
export * from './passes/function-virtualization.js';
