import { app, BrowserWindow, ipcMain } from 'electron';
import path from 'path';

export function createSecureWindow() {
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      // Electron hardening policy applied by TS-VM-Obfuscator plugin
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: true,
      preload: path.join(__dirname, 'preload.js'),
    }
  });

  // Example of IPC sender validation
  ipcMain.handle('secure-action', (event, data) => {
    if (event.senderFrame?.url !== 'file://' + path.join(__dirname, 'index.html')) {
      throw new Error('Unauthorized sender');
    }
    // Protected logic
    return 'success';
  });

  win.loadFile('index.html');
}

app.whenReady().then(createSecureWindow);

// Fuse configuration (to be generated by the hardening package)
// EnableEmbeddedAsarIntegrityValidation: true
// OnlyLoadAppFromAsar: true
// RunAsNode: false
// EnableNodeCliInspectArguments: false
